M48
; DRILL file {KiCad 9.0.1} date 2025-04-27T12:11:08+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-27T12:11:08+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X5.03Y13.4
X5.03Y7.62
T2
X1.51Y17.0
X1.51Y4.0
X49.51Y17.0
X49.51Y4.0
M30
