M48
; DRILL file {KiCad (6.0.9)} date Sat Jan  7 18:48:59 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-07T18:48:59+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X7.61Y45.92
X13.41Y45.92
T2
X4.0Y49.49
X4.0Y1.49
X17.0Y49.49
X17.0Y1.49
T0
M30
